on:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - '24.2.1'
          - '24.4.1'
          - '24.5.1'
          - '24.5.3'
          - '24.6.1'
          - '24.6.2'
          - '24.7.1'
          - '24.7.2'
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5 # v3
      - run: curl https://unified-agent.s3.amazonaws.com/wss-unified-agent-${{ matrix.version }}.jar -o mend-ua.jar
      - run: java -jar mend-ua.jar -offline true -project mend-pnpm-repro -logLevel debug -npm.includeDevDependencies true
      - run: cat whitesource/update-request.txt
